Repository Bluemoonside/ProyectoEncuestaCreatividad, pull requests merged in 2023-01, with the labels that each got.

#42 Cree Crud de escala
  Metrics/forms.py
  Metrics/templates/createdScale.html
  Metrics/templates/deleteScale.html
  Metrics/templates/listScale.html
  Metrics/templates/updateScale.html
  Metrics/urls.py
  Metrics/views.py
  Models/migrations/0014_alter_question_pub_date.py
  Models/migrations/__pycache__/__init__.cpython-311.pyc
  Models/models/Scale.py
Labels: fd:Done

#54 Separando las views de la app metrics
  Metrics/Views/DimensionViews/DimensionCreateViews.py
  Metrics/Views/DimensionViews/DimensionDeleteView.py
  Metrics/Views/DimensionViews/DimensionListView.py
  Metrics/Views/DimensionViews/DimensionUpdateView.py
  Metrics/Views/IndicatorsViews/IndicatorCreateView.py
  Metrics/Views/IndicatorsViews/IndicatorDeleteView.py
  Metrics/Views/IndicatorsViews/IndicatorListView.py
  Metrics/Views/IndicatorsViews/IndicatorUpdateView.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionCreateView.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionDeleteView.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionListViews.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionUpdateView.py
  Metrics/Views/ScaleViews/ScaleCreateView.py
  Metrics/Views/ScaleViews/ScaleDeleteView.py
  Metrics/Views/ScaleViews/ScaleListView.py
  Metrics/Views/ScaleViews/ScaleUpdateView.py
  Metrics/Views/VariableViews/VariableCreateView.py
  Metrics/Views/VariableViews/VariableDeleteView.py
  Metrics/Views/VariableViews/VariableListView.py
  Metrics/Views/VariableViews/VariableUpdateView.py
  Metrics/urls.py
  Metrics/views.py
Labels: enhancement

#63 Arreglando las vistas html
  Metrics/templates/base.html
  Metrics/templates/createdDimension.html
  Metrics/templates/createdIndicator.html
  Metrics/templates/createdMeasurementCriterion.html
  Metrics/templates/createdScale.html
  Metrics/templates/createdVariable.html
  Metrics/templates/deleteDimension.html
  Metrics/templates/deleteIndicator.html
  Metrics/templates/deleteMeasurementCriterion.html
  Metrics/templates/deleteScale.html
  Metrics/templates/deleteVariable.html
  Metrics/templates/listDimension.html
  Metrics/templates/listIndicator.html
  Metrics/templates/listMeasurementCriterion.html
  Metrics/templates/listScale.html
  Metrics/templates/listVariable.html
  Metrics/templates/updateDimension.html
  Metrics/templates/updateIndicator.html
  Metrics/templates/updateMeasurementCriterion.html
  Metrics/templates/updateScale.html
  Metrics/templates/updateVariable.html
  Metrics/urls.py
  Poll/templates/createpoll.html
Labels: Finished

#64 Tablas con sentido
  Metrics/templates/listDimension.html
  Metrics/templates/listIndicator.html
  Metrics/templates/listMeasurementCriterion.html
  Metrics/templates/listScale.html
  Models/models/Dimension.py
  Models/models/Indicator.py
  Models/models/Variable.py
Labels: Finished

#68 Arreglos Hechos Para el Corte de Mañana
  Metrics/templates/metricsbase.html
  Metrics/urls.py
  Models/migrations/0016_merge_20230102_1454.py
  Models/migrations/0016_merge_20230102_1624.py
  Models/migrations/0017_remove_dimension_indicators_and_more.py
  Models/migrations/__init__.py
  Poll/templates/createpoll.html
  Poll/templates/createquestion.html
  Poll/templates/deletepoll.html
  Poll/templates/deletequestion.html
  Poll/templates/pollbase.html
  Poll/templates/polllist.html
  Poll/templates/questionlist.html
  Poll/templates/updatepoll.html
  Poll/templates/updatequestion.html
  ProyectoEncuestaCreatividad/templates/basecontain.html
  static/css/gestion.css
Labels: enhancement

#70 Otros Arreglos
  Metrics/Forms/DimensionForm.py
  Metrics/Forms/IndicatorForm.py
  Metrics/Forms/MeasurementCriterionForm.py
  Metrics/Forms/ScaleForm.py
  Metrics/Forms/VariableForm.py
  Metrics/Forms/forms.py
  Metrics/Views/DimensionViews/DimensionCreateViews.py
  Metrics/Views/DimensionViews/DimensionDeleteView.py
  Metrics/Views/DimensionViews/DimensionListView.py
  Metrics/Views/DimensionViews/DimensionUpdateView.py
  Metrics/Views/IndicatorsViews/IndicatorCreateView.py
  Metrics/Views/IndicatorsViews/IndicatorDeleteView.py
  Metrics/Views/IndicatorsViews/IndicatorListView.py
  Metrics/Views/IndicatorsViews/IndicatorUpdateView.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionCreateView.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionDeleteView.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionListViews.py
  Metrics/Views/MeasurementCriterionViews/MeasurementCriterionUpdateView.py
  Metrics/Views/ScaleViews/ScaleCreateView.py
  Metrics/Views/ScaleViews/ScaleDeleteView.py
  Metrics/Views/ScaleViews/ScaleListView.py
  Metrics/Views/ScaleViews/ScaleUpdateView.py
  Metrics/Views/VariableViews/VariableCreateView.py
  Metrics/Views/VariableViews/VariableDeleteView.py
  Metrics/Views/VariableViews/VariableListView.py
  Metrics/Views/VariableViews/VariableUpdateView.py
  Metrics/forms.py
  Metrics/templates/listMeasurementCriterion.html
  Poll/Forms/PollForm.py
  Poll/Forms/QuestionForm.py
  Poll/Views/PollViews/PollCreateView.py
  Poll/Views/PollViews/PollDeleteView.py
  Poll/Views/PollViews/PollListView.py
  Poll/Views/PollViews/PollUpdateView.py
  Poll/Views/QuestionViews/QuestionCreateView.py
  Poll/Views/QuestionViews/QuestionDeleteView.py
  Poll/Views/QuestionViews/QuestionListView.py
  Poll/Views/QuestionViews/QuestionUpdateView.py
  Poll/forms.py
  Poll/urls.py
  Poll/views.py
Labels: enhancement

#78 77 limpiar errores de formato de escritura segun flake
  .flake8
  .github/workflows/django.yml
  Metrics/Forms/ScaleForm.py
Labels: bug
